apps:
  - name: 'apache2'
    script: 'service'
    args: 'apache2 start'
    interpreter: 'bash'
  - name: 'jellyfishScheduler'
    script: '/var/www/jellyfish/releases/current/vendor/bin/console'
    args: 'scheduler:work'
    interpreter: 'php'
  - name: 'jellyfishEventQueueWorker'
    script: '/var/www/jellyfish/releases/current/vendor/bin/console'
    args: 'event:queue:worker'
    interpreter: 'php'
