name: Build docker images

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test Build all docker images
        run: make test-all
