name: Build and push docker images

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.4, 8.0, 8.1, 8.2]
        os: [alpine, debian]
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: make login
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push all docker images
        run: make build-all
        env:
          PHP_VERSIONS: ${{ matrix.version }}
          LINUX_DISTRIBUTIONS: ${{ matrix.os }}
