name: Build and push docker images

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: make login
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push all docker images
        run: make build-all
