name: Docker Image CI

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: DOCKER_HUB_USERNAME= make login
      - name: Build docker images
        run: make buildDockerImages
      - name: Push docker images
        run: make pushDockerImages
